
cron: "10 */15 * * * *"                           # Execution every 15 minutes at 10'th second 
logLevel: 4                                       # Logging level
params:
  apiEndpoint: "http://localhost:8080/api"        # API endpoint to call
  token: "Bearer YOUR_TOKEN"                      # Authorization token (replace with real one)
  pccImportLimitW: 50000                          # PCC limit energy import
  pccExportLimitW: -1000000                       # PCC limit power export
  essMinSafeLim: "ess_min_batt_safe_lim"
  essPowerLimitW: 175000                          # ESS power limit
  essMaxCharge: 284000                            # ESS max charge
  productionPrognosisIdentifier: "production_p_lt"    # Production forecast values
  consumptionPrognosisIdentifier: "consumption_p_lt"  # Consumption forecast values
  essCurrentPowerPlanIdentifier: "ess_p_lt_a5"        # Previous prognosis that is used in case optimization fails
  essResultPowerPlanIdentifier: "ess_p_lt_a1"         # Result prognosis
  essEffectiveCharge: "ess_charge"                    # effective storage charge at the beginning of optimization(may be negative)
  essEffectiveEndCharge: "ess_charge"                 # effective charge of the storage device at the end of optimization
  interval: 900
  min_period: 21600
